let lessons = [    
    {"subject":"Maths", 
        "id":1,
        "location":"hendon", 
        "price":100, 
        "space":5, 
        "image":"images/maths.png", 
        "icon": "f1ec"},    
    {"subject":"English", 
        "id":2,
        "location":"edgware", 
        "price":90, 
        "space":5,   
        "image":"images/english.png", 
        "icon": "fas fa-calculator"},     
    {"subject":"Science", 
        "id":3,
        "location":"wembley", 
        "price":100, 
        "space":5,
        "image":"images/science.jpg", 
        "icon": "fas fa-calculator"},            
    {"subject":"History", 
        "id":4,
        "location":"hendon", 
        "price":150, 
        "space":5,
        "image":"images/history.jpg", 
        "icon": "fas fa-calculator"},        
    {"subject":"Geography",
        "id":5,
        "location":"edgware", 
        "price":100, 
        "space":5, 
        "image":"images/geo.jpg", 
        "icon": "fas fa-calculator"},       
    {"subject":"Design & technology",
        "id":6,
        "location":"wembley", 
        "price":100, 
        "space":5,  
        "image":"images/design.jpg", 
        "icon": "fas fa-calculator"},      
    {"subject":"Art & design", 
        "id":7,
        "location":"hendon", 
        "price":60, 
        "space":5, 
        "image":"images/art.png", 
        "icon": "fas fa-calculator"},       
    {"subject":"Music",
        "id":8, 
        "location":"wembley", 
        "price":100, 
        "space":5,  
        "image":"images/music.jpg", 
        "icon": "fas fa-calculator"},      
    {"subject":"Computing", 
        "id":9,
        "location":"hendon", 
        "price":70, 
        "space":5,
        "image":"images/computing.jpg", 
        "icon": "fas fa-calculator"},        
    {"subject":"Physical education", 
        "id":10,
        "location":"edgware", 
        "price":115, 
        "space":5 ,
        "image":"images/pe.png", 
        "icon": "fas fa-calculator"}  
]  